# Generated by Django 4.0 on 2025-10-27 14:00

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coms', '0003_interclientmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, default='assets/imgs/resources/profiledefault.png', max_length=512, null=True, upload_to=auth_app.models.get_file_path, verbose_name='Image'),
        ),
    ]
