# Generated by Django 4.0 on 2025-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkout_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
