# Generated by Django 4.0 on 2025-10-27 13:59

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='image',
            field=models.FileField(default='test/django.png', max_length=512, upload_to=auth_app.models.get_file_path, verbose_name='Business Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='assets/imgs/resources/profiledefault.png', max_length=512, null=True, upload_to=auth_app.models.get_file_path, verbose_name='Image'),
        ),
    ]
