# Generated by Django 4.0 on 2025-07-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_order_is_complete_alter_product_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
