# Generated by Django 4.0 on 2025-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_order_is_complete_alter_product_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderproductvariation',
            name='color',
        ),
        migrations.AddField(
            model_name='orderproductvariation',
            name='color',
            field=models.ManyToManyField(blank=True, to='supplier.ProductColor'),
        ),
        migrations.RemoveField(
            model_name='orderproductvariation',
            name='material',
        ),
        migrations.AddField(
            model_name='orderproductvariation',
            name='material',
            field=models.ManyToManyField(blank=True, to='supplier.ProductMaterial'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_ar',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_de',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name_fr',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='name_ar',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='name_de',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='name_fr',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
    ]
