# Generated by Django 4.0 on 2025-07-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_checkout_id_and_more'),
        ('supplier', '0003_alter_order_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction'),
        ),
    ]
