# Generated by Django 4.0 on 2025-08-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_order_payment_alter_order_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='PAID', max_length=256, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_ar',
            field=models.CharField(choices=[('PAID', 'PAID'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='PAID', max_length=256, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_de',
            field=models.CharField(choices=[('PAID', 'PAID'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='PAID', max_length=256, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('PAID', 'PAID'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='PAID', max_length=256, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_fr',
            field=models.CharField(choices=[('PAID', 'PAID'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='PAID', max_length=256, null=True, verbose_name='Order Status'),
        ),
    ]
