# Generated by Django 4.0 on 2025-08-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_alter_order_status_alter_order_status_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductvariation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier.order'),
        ),
    ]
