# Generated by Django 4.0 on 2025-10-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_alter_orderproductvariation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Safe Url'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Safe Url'),
        ),
    ]
