# Generated by Django 4.0 on 2025-10-27 13:59

from django.db import migrations, models
import supplier.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_alter_productimage_slug_alter_productvideo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.FileField(default='test/django.png', max_length=512, upload_to=supplier.models.get_file_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(max_length=512, upload_to=supplier.models.get_file_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='image',
            field=models.FileField(default='test/django.png', max_length=512, upload_to=supplier.models.get_file_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(max_length=512, upload_to=supplier.models.get_file_path, verbose_name='Service Image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FileField(default='test/django.png', max_length=512, upload_to=supplier.models.get_file_path, verbose_name='Service Image'),
        ),
    ]
