# Generated by Django 4.0 on 2025-07-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Web Designer', 'Web Designer'), ('Web Developer', 'Web Developer'), ('Mobile App Designer', 'Mobile App Designer'), ('Mobile App Developer', 'Mobile App Developer'), ('Digital Marketer', 'Digital Marketer')], max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
