# Generated by Django 4.0 on 2025-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
