# Generated by Django 4.0 on 2025-10-27 13:54

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_careerapplication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpromotion',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=manager.models.get_file_path, verbose_name='Image'),
        ),
    ]
