# Generated by Django 4.0 on 2025-10-27 13:59

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_emailpromotion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=manager.models.get_file_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(max_length=512, upload_to=manager.models.get_file_path, verbose_name='Service Image'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='image',
            field=models.ImageField(default='test/django.png', max_length=512, upload_to=manager.models.get_file_path, verbose_name='Image'),
        ),
    ]
