# Generated by Django 4.0 on 2025-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_promotion_image_alter_serviceimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
