# Generated by Django 4.0 on 2025-10-29 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_onboarding_servicebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='Intro'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='manager.service')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
