# Generated by Django 4.0 on 2025-10-29 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_service_intro_service_subtitle_serviceimage_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_de',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_fr',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(max_length=512, upload_to=manager.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manager.service'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
